experimental_monorepo_root = true

[monorepo]
config_roots = [
    "bootstrap",
    "talos",
    "talos/*",
]

[env]
_.python.venv = {path = "{{config_root}}/.venv", create = true}
# CLUSTER = "main"
BWS_ACCESS_TOKEN = {required = true}
CLUSTER = "steamdeck"
SHARED_APPS = "{{config_root}}/kubernetes/apps/main"
CLUSTER_APPS = "{{config_root}}/kubernetes/apps/{{env.CLUSTER}}"
KUBECONFIG = "{{config_root}}/kubernetes/clusters/{{env.CLUSTER}}/kubeconfig"
MINIJINJA_CONFIG_FILE = "{{config_root}}/.minijinja.toml"
MISE_EXPERIMENTAL = 1
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/{{env.CLUSTER}}/talosconfig"
TALOS_DIR = "{{config_root}}/talos/{{env.CLUSTER}}"

[tools]
"aqua:FiloSottile/age" = "1.3.1"
"aqua:budimanjojo/talhelper" = "3.1.9"
"aqua:charmbracelet/gum" = "0.17.0"
"aqua:cilium/cilium-cli" = "0.19.2"
"aqua:cloudflare/cloudflared" = "2026.3.0"
"aqua:cue-lang/cue" = "0.16.1"
"aqua:evilmartians/lefthook" = "2.1.6"
"aqua:fluxcd/flux2" = "2.8.6"
"aqua:getsops/sops" = "3.12.2"
"aqua:go-task/task" = "3.50.0"
"aqua:google/yamlfmt" = "0.21.0"
"aqua:helm/helm" = "4.1.4"
"aqua:helmfile/helmfile" = "1.4.4"
"aqua:jqlang/jq" = "1.7.1"
"aqua:kubernetes-sigs/kustomize" = "5.6.0"
"aqua:kubernetes/kubectl" = "1.33.1"
"aqua:mikefarah/yq" = "4.53.2"
"aqua:mitsuhiko/minijinja" = "2.19.0"
"aqua:siderolabs/talos" = "1.13.0"
"aqua:yannh/kubeconform" = "0.7.0"
"github:cli/cli" = "2.92.0"
"pipx:makejinja" = "2.8.2"
"python" = "3.14.4"

[tasks.log]
quiet = true
run = 'gum log -t rfc3339 -s -l "${usage_lvl?}" "${usage_msg?}" ${usage_args}'
usage = '''
arg "<lvl>"
arg "<msg>"
arg "[args]" var=#true
'''

[tasks.template]
quiet = true
run = '''
bws run -- minijinja-cli ${usage_input?} ${usage_args}
'''
usage = '''
arg "<input>"
arg "[args]" var=#true
'''
