---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name explo-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        LISTENBRAINZ_USER: "{{ .LZ_USER }}"
        LISTENBRAINZ_USER_TOKEN: "{{ .LZ_TOKEN }}"
        API_KEY: "{{ .PLEX_TOKEN }}"
        SLSKD_API_KEY: "{{ .SLSKD_API_KEY }}"
  dataFrom:
    - extract:
        key: multiscrobbler
    - extract:
        key: plex
    - extract:
        key: soulseek
