{
 "title": "bitmagnet",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bitmagnet_process_resident_memory_bytes",
     "legendFormat": "Process Memory"
    }
   ]
  },
  {
   "title": "DHT crawler torrents persisted per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_crawler_persisted_total[$__rate_interval])*60",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Queue jobs count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(bitmagnet_queue_jobs_total[$__rate_interval])",
     "legendFormat": "{{queue}}:{{status}}"
    }
   ]
  },
  {
   "title": "Warnings & Errors",
   "type": "logs",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"bitmagnet\"} | json | severity = \"WARNING\" or severity = \"ERROR\""
    }
   ]
  },
  {
   "title": "DHT query success per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_queries_total{status=\"success\"}[$__rate_interval])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT query errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(bitmagnet_dht_queries_total{status!=\"success\"}[$__rate_interval])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "DHT query latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(bitmagnet_dht_query_duration_milliseconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DHT query concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(bitmagnet_dht_query_concurrency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request success per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "rate(bitmagnet_metainfo_requests_total{status=\"success\"}[$__rate_interval])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(bitmagnet_metainfo_requests_total{status!=\"success\"}[$__rate_interval])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Meta info request latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(bitmagnet_metainfo_request_duration_milliseconds_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Meta info request concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(bitmagnet_metainfo_request_concurrency)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Classifier success per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "rate(bitmagnet_classifier_workflow_runs_total{status=\"success\"}[$__rate_interval])*60",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Classifier latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(bitmagnet_classifier_workflow_duration_milliseconds_bucket[$__rate_interval]))",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Classifier latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(bitmagnet_classifier_workflow_duration_milliseconds_bucket[$__rate_interval]))",
     "legendFormat": "{{workflow}}"
    }
   ]
  }
 ]
}