---
# yaml-language-server: $schema=https://json.schemastore.org/persistentvolumeclaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agregarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-block
