---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app dawarich
spec:
  releaseName: dawarich
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  dependsOn: []
  values:
    controllers:
      dawarich:
        containers:
          app: &dawarich
            image:
              repository: mirror.gcr.io/freikin/dawarich
              tag: 1.7.11@sha256:531a649c7e96d5c182834b1628103d70f0d020d9285d2c9367d73f9e34164e1f
            env:
              TIME_ZONE: "Europe/Paris"
              PHOTON_API_HOST: photon.default.svc.cluster.local:2322
              PHOTON_API_USE_HTTPS: false
              SELF_HOSTED: "true"
              STORE_GEODATA: "true"
              DISTANCE_UNIT: km
              APPLICATION_HOSTS: "dawarich.${SECRET_DOMAIN}"
              REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379
              RAILS_ENV: production
              DATABASE_NAME: *app
              DATABASE_PORT: 5432
              DATABASE_HOST: postgres-dawarich-rw.default.svc
              DATABASE_USERNAME: *app
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: postgres-dawarich-app
                    key: password
            envFrom:
              - secretRef:
                  name: dawarich-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/health
                    port: &port 3000
              readiness: *probe
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "4Gi"
                cpu: "3000m"
            command:
              - "web-entrypoint.sh"
            args:
              - "bin/rails"
              - "server"
              - "-p"
              - "3000"
              - "-b"
              - "0.0.0.0"
          sidekiq:
            <<: *dawarich
            command:
              - "sidekiq-entrypoint.sh"
            args:
              - "sidekiq"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            securityContext: *securityContext
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "6Gi"
                cpu: "3000m"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Dawarich
          gethomepage.dev/icon: google-maps.png
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: network
    persistence:
      data:
        existingClaim: dawarich
        globalMounts:
          - path: /var/app/public
            subPath: public
          - path: /var/app/storage
            subPath: storage
      watched:
        type: emptyDir
        globalMounts:
          - path: /var/app/tmp/imports/watched
