---
name: smartctl-exporter

services:
  smartctl-exporter:
    image: quay.io/prometheuscommunity/smartctl-exporter:v0.14.0
    container_name: smartctl-exporter
    restart: unless-stopped
    privileged: true
    user: root
    command:
      - --smartctl.device-exclude=nvme0
    ports:
      - "9633:9633"
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 32m
