---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/zeroscaler
    - ../../../../../components/postgres-vchord
    # - ../../../../../components/cnpg/import
    - ../../../../../components/gpu
  dependsOn:
    - name: crunchy-postgres-operator
      namespace: database
    - name: plugin-barman-cloud
      namespace: database
  healthCheckExprs:
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 30m
  path: ./kubernetes/apps/main/default/immich/app
  patches:
    - target:
        group: postgresql.cnpg.io
        version: v1
        kind: Cluster
      patch: |-
        - op: add
          path: /spec/postgresql/shared_preload_libraries
          value:
            - vchord.so
        - op: add
          path: /spec/postgresql/extensions
          value:
            - name: vchord
              image:
                reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
              dynamic_library_path:
                - /usr/lib/postgresql/18/lib
              extension_control_path:
                - /usr/share/postgresql/18/
  postBuild:
    substitute:
      APP: *app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false # no flux ks dependents
