---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app komga
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/zeroscaler
    - ../../../../../components/kopiur/backup
    - ../../../../../components/oidc
  path: ./kubernetes/apps/main/media/komga/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
      APP_NAMESPACE: *namespace
      KOPIUR_SCHEDULE: "35 * * * *"
      KOPIUR_CAPACITY: 2Gi
      OIDC_DISPLAY_NAME: Komga
      OIDC_CALLBACK: /login/oauth2/code/kanidm
      OIDC_SHORT_USERNAME: "true"
      OIDC_DISABLE_PKCE: "true"
      OIDC_LEGACY_CRYPTO: "true"
      OIDC_CLIENT_ID_KEY: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KANIDM_CLIENT_ID
      OIDC_CLIENT_SECRET_KEY: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KANIDM_CLIENT_SECRET
