---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name nextcloud-secret
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        nextcloud-username: "{{ .NEXTCLOUD_ADMIN_USER }}"
        nextcloud-password: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        # smtp-username: "{{ .SMTP_USERNAME }}"
        # smtp-password: "{{ .SMTP_PASSWORD }}"
        # smtp-host: "{{ .SMTP_HOST }}"
        # redis-password: "{{ .REDIS_PASSWORD }}"
        # oidc-client-secret: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: nextcloud
