---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-data
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-data
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NFS_ADDR}
    path: /mnt/tank/backup/nextcloud
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nextcloud-data
  resources:
    requests:
      storage: 2Ti
