---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app paperless
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/dragonfly
    - ../../../../../components/zeroscaler
    - ../../../../../components/volsync
    - ../../../../../components/cnpg/restore
  dependsOn:
    - name: plugin-barman-cloud
      namespace: database
  healthCheckExprs:
    - apiVersion: dragonflydb.io/v1alpha1
      kind: Dragonfly
      failed: status.phase != 'ready'
      current: status.phase == 'ready'
    - apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 30m
  path: ./kubernetes/apps/main/default/paperless/app
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false # no flux ks dependents
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 15Gi
---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-gpt
  namespace: &namespace default
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless-gpt
  components:
    - ../../../../../../../components/volsync
  dependsOn:
    - name: paperless
  interval: 30m
  path: ./kubernetes/apps/main/default/paperless/app/tools/paperless-gpt
  prune: true
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: paperless-gpt
      VOLSYNC_CAPACITY: 1Gi
